package com.cratechnologie.financialmanagement.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransactionLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionLogAllPropertiesEquals(TransactionLog expected, TransactionLog actual) {
        assertTransactionLogAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionLogAllUpdatablePropertiesEquals(TransactionLog expected, TransactionLog actual) {
        assertTransactionLogUpdatableFieldsEquals(expected, actual);
        assertTransactionLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionLogAutoGeneratedPropertiesEquals(TransactionLog expected, TransactionLog actual) {
        assertThat(expected)
            .as("Verify TransactionLog auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionLogUpdatableFieldsEquals(TransactionLog expected, TransactionLog actual) {
        assertThat(expected)
            .as("Verify TransactionLog relevant properties")
            .satisfies(e -> assertThat(e.getAction()).as("check action").isEqualTo(actual.getAction()))
            .satisfies(e -> assertThat(e.getActionAt()).as("check actionAt").isEqualTo(actual.getActionAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionLogUpdatableRelationshipsEquals(TransactionLog expected, TransactionLog actual) {
        assertThat(expected)
            .as("Verify TransactionLog relationships")
            .satisfies(e -> assertThat(e.getTransaction()).as("check transaction").isEqualTo(actual.getTransaction()));
    }
}
